export default {
  web3: {
    networkId: null,
    coinbase: null,
    balance: '0',
    isConnected: false,
    contractAddress: '0',
    contractBalance: '0',
  },
  player: {
    prizeAmount: '0',
    prizeGameID: '0',
    purchasedTicket: {
      ticketValue: '0',
      number1: '0',
      number2: '0',
      position: '0',
      difference: '0',
      received: true,
      lucky7Ticket: false,
      gameID: '0',
      ticketID: '0',
    },
    generatedTicket: {
      ticketValue: '0',
      number1: '0',
      number2: '0',
      position: 1,
      difference: 0,
      received: true,
      lucky7Ticket: false,
      gameID: '0',
    },
  },
  game: {
    settings: {
      b: '0',
      n: '0',
      p: '0',
      j: '0',
      storeEnabled: true,
      gameID: '0',
    },
    stats: {
      randomTickets: '0',
      generatedTickets: '0',
      generatedTicketsSelled: '0',
      contractBalance: '0',
    },
    prices: {
      generate: '0',
      purchase: '0',
    },
  },
  lucky7GameInfo: [],
  lucky7GameInfoReady: false,
  lucky7PastGames: [],
};
