export default {
  web3: {
    networkId: null,
    coinbase: null,
    balance: '0',
    isConnected: false,
    contractAddress: '0',
    contractBalance: '0',
  },
  player: {
    currentPrize: '0',
    prizeGameID: 0,
    lastPurchasedTicket: '0',
    lastPurchasedTicketID: '0',
    lastNumberGenerated1: '0',
    lastNumberGenerated2: '0',
    lastNumberPurchased1: '0',
    lastNumberPurchased2: '0',
    isLucky7Ticket: false,
    firstGenerateNumberReceived: true,
    secondGenerateNumberReceived: true,
    firstPurchaseNumberReceived: true,
    secondPurchaseNumberReceived: true,
    purchasedTicketReceived: true,
    generatedTicketReceived: true,
    userTicketsCounter: 0,
    lastPurchasedTicketGameID: '0',
    lastGeneratedTicketGameID: '0',
  },
  game: {
    b: '0',
    n: '0',
    p: '0',
    j: '0',
    generateTicketPrice: '0',
    purchaseTicketPrice: '0',
    randomTicketsSelled: 0,
    generatedTickets: 0,
    generatedTicketsSelled: 0,
    settingLucky7Numbers: true,
    gameID: '0',
  },
  lucky7GameInfo: [],
  lucky7PastGames: [],
};
